export const remarks = [
  "All fast alongside",
  "Anchor up",
  "Arrived at roads",
  "Awainting Customs Clearence",
  "Awaiting anvisa liberation",
  "Awaiting Autorization for Loading Cargo",
  "Awaiting berthing",
  "Awaiting Berthing In Siscomex",
  "Awaiting Boat for check the drafts",
  "Awaiting Cargo",
  "Awaiting Cargo Readiness",
  "Awaiting Clearance Cargo",
  "Awaiting custom documentation",
  "Awaiting custom inspection",
  "Awaiting Draft Surveyor",
  "Awaiting For Stevedores",
  "Awaiting Gangway Down",
  "Awaiting Gas Free Inspections",
  "Awaiting hatch/hold opening",
  "Awaiting high tide",
  "Awaiting Hold Inspection",
  "Awaiting Holds Inspection",
  "Awaiting low tide",
  "Awaiting unberth tide time",
  "Awaiting Release By The Authorities",
  "Awaiting Release Of  The Ship",
  "Awaiting Release Of  The Vessel To Load",
  "Awaiting ship`s Orders",
  "Awaiting surveyor by Terminal",
  "Awaiting Terminal instructions",
  "Bad Weather ( Heavy Rain)",
  "BlackOut",
  "Bulldozer breakdown",
  "Calibration of Shore Scale",
  "Cargo quality inspection",
  "Cargo trimming",
  "Checking Draft Cargo Vessel",
  "Completed loading",
  "Dirty Holds",
  "Discharge Completed",
  "Draft Survey",
  "Draft survey commenced",
  "Draft survey completed",
  "Dropped anchor outer roads",
  "Eletrical Failure",
  "Equipment Handled To The Project Maintenance",
  "Failure at Shiploader",
  "Final Draft Survey By official surveyor",
  "Final Draft Survey By official surveyor GMS",
  "Final Draft Survey By official surveyor INTERTEK",
  "Final Draft Survey By official surveyor MULTIVISTA",
  "Final Draft Survey By official surveyor SCHUTTER",
  "Final Draft Survey By official surveyor COTECNA",
  "Final Draft Survey By official surveyor SGS",
  "Final Draft Survey By official surveyor SUPERINSPECT",
  "Final Draft Survey By official surveyor VLI",
  "First Line ashore",
  "Free Pratique Granted",
  "Gangway Down",
  "Grab maintenance",
  "High Temperature Compressor",
  "Initial draft",
  "Initial Draft Survey By official surveyor GMS",
  "Initial Draft Survey By official surveyor INTERTEK",
  "Initial Draft Survey By official surveyor LIGHTSHIP GROUP",
  "Initial Draft Survey By official surveyor SCHUTTER",
  "Initial Draft Survey By official surveyor COTECNA",
  "Initial Draft Survey By official surveyor MULTIVISTA",
  "Initial Draft Survey By official surveyor SGS",
  "Initial Draft Survey By official surveyor SUPERINSPECT",
  "Initial Draft Survey By official surveyor VLI",
  "Inspection At The Shiploader",
  "Intermediate Draft Survey By official surveyor GMS",
  "Intermediate Draft Survey By official surveyor INSPECTORATE",
  "Intermediate Draft Survey By official surveyor SCHUTTER",
  "Intermediate Draft Survey By official surveyor SGS",
  "Intermediate Draft Survey By official surveyor SUPERINSPECT",
  "Intermediate Draft Survey By  VLI",
  "International holliday",
  "Lack of  fire water",
  "Loading",
  "Loading in Progress",
  "Loading ships consumption",
  "Loading ships lub oil drums",
  "Loading Stopped due Air Draft",
  "Loading Stopped due to Bad Weather ( Heavy Rain)",
  "Loading Stopped due to Deballasting required by Master",
  "Loading Stopped due to Dirty Holds",
  "Loading Stopped due to Eletrical Failure",
  "Loading Stopped due to Meal Break Terminal",
  "Loading Stopped due to Mechanical Failure",
  "Loading Stopperd due to Strong Wind",
  "Loading was interrupted for draft survey as per captains order",
  "Loading",
  "Maintenance",
  "Maintenance  In Shore Scale",
  "Maintenance At Shiploader",
  "Mechanical Failure",
  "Notice of readness accepted",
  "Notice of readness tendered",
  "Overload Cargo In Shore Scale",
  "Pilot off",
  "Pilot on board for berthing",
  "Pilot on board for shifting",
  "Place ship's material on board",
  "Eletric Power Off (blackout)",
  "Preparation ashore",
  "Quality Surveyor Checking",
  "Rain",
  "Sailing to the bar",
  "Shift change at Terminal",
  "Shifting from Anchorage Area to Berthing untill first line",
  "Shifting hold from #1 to #2",
  "Shifting hold from #1 to #3",
  "Shifting hold from #1 to #4",
  "Shifting hold from #1 to #5",
  "Shifting hold from #1 to #6",
  "Shifting hold from #1 to #7",
  "Shifting hold from #2 to #1",
  "Shifting hold from #2 to #3",
  "Shifting hold from #2 to #4",
  "Shifting hold from #2 to #5",
  "Shifting hold from #2 to #6",
  "Shifting hold from #2 to #7",
  "Shifting hold from #3 to #1",
  "Shifting hold from #3 to #2",
  "Shifting hold from #3 to #4",
  "Shifting hold from #3 to #5",
  "Shifting hold from #3 to #6",
  "Shifting hold from #3 to #7",
  "Shifting hold from #4 to #1",
  "Shifting hold from #4 to #2",
  "Shifting hold from #4 to #3",
  "Shifting hold from #4 to #5",
  "Shifting hold from #4 to #6",
  "Shifting hold from #4 to #7",
  "Shifting hold from #5 to #1",
  "Shifting hold from #5 to #2",
  "Shifting hold from #5 to #3",
  "Shifting hold from #5 to #4",
  "Shifting hold from #5 to #6",
  "Shifting hold from #5 to #7",
  "Shifting hold from #6 to #1",
  "Shifting hold from #6 to #2",
  "Shifting hold from #6 to #3",
  "Shifting hold from #6 to #4",
  "Shifting hold from #6 to #5",
  "Shifting hold from #6 to #7",
  "Shifting hold from #7 to #1",
  "Shifting hold from #7 to #2",
  "Shifting hold from #7 to #3",
  "Shifting hold from #7 to #4",
  "Shifting hold from #7 to #5",
  "Shifting hold from #7 to #6",
  "Ship's gangway breakdown",
  "Shiploader Preparing",
  "Stevedores changing shift",
  "Stop Request By Port Authority (EMAP)",
  "Strike",
  "System Cleanup",
  "System Defect",
  "Tally men and stevedores not required due strike",
  "Testing ship's machines",
  "Trimming",
  "Tripper At Shiploader Blocked",
  "Vessel achored at roads awaiting for berthing (Berth unavailble)",
  "Vessel arrived at Roads",
  "Vessel unberthed",
  "Waiting for Pallets Placement Inside Holds",
  "Loading Stopped due to elevated airdraft (awaiting low tide)",
  "FUMIGATION",
  "All holds inspected and found not suitable regarding cleanliness condition for grains loading",
  "Awaiting Pilot Comply. with Port Regulations for Maneuvers.",
  "System Drainage",
];
