"use client";

import { Header } from "@/components/Header";
import { Sidebar } from "@/components/Sidebar";
//Quando se usa use cliente não da pra usar essa metadata
// export const metadata = {
//   title: "Núcleo System",
//   description: "Generated by www.mannatech.com.br",
// };

// import { theme } from "@/styles/theme";
import { Flex } from "@chakra-ui/react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Flex direction="column" h="100vh">
      <Header />
      <Flex w="100%" my="6" maxWidth={1480} h="auto" mx="auto" px="6">
        <Sidebar />
        {children}
      </Flex>
    </Flex>
  );
}
